server:
  port: 8002

spring:
  application:
    name: cloud-payment-service
  cloud:
    zookeeper:
      connect-string: node10:2181,node11:2181,node12:2181
      discovery:
        register: true
        enabled: true
        instance-id: 2
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&&characterEncoding=utf-8&&useSSL=false
    username: root
    password: 1705020111
feign:
  hystrix:
    enable: true

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:7001/eureka
#  instance:
#    instance-id: payment8002

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.misaka.springcloud.entities